# https://docs.minecraftforge.net/en/latest/gettingstarted/modfiles/
modLoader="javafml"
loaderVersion="[46,)"
license="todo"
showAsResourcePack=false

[[mods]]
modId="cssminecraft"
version="${version}"
displayName="CSSMinecraft"
logoFile="logo.png"
authors="LMBishop"
description='''
  CSS' Minecraft plugin
  '''

[[dependencies.luckperms]]
modId="luckperms"
mandatory=false
versionRange=""
ordering="AFTER"
side="SERVER"
