name: CSSMinecraft
version: '${version}'
main: com.cssbham.cssminecraft.bukkit.CSSMinecraftLoader
api-version: 1.21 # probably
authors: [ RaineTheBoosted, LMBishop ]
description: CSS' Minecraft plugin
website: https://github.com/CSSUoB/CSS-Minecraft
softdepend: [ LuckPerms ] # TODO change back to depends
commands:
  makegreen:
    description: Make yourself green by verifying your CSS membership.
    usage: /<command> [Discord Username]
    aliases: [ mg, green ]